---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        platform: [ubuntu-latest]

    runs-on: $

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install pnpm
        run: corepack enable
      - name: Use Node.js $
        uses: actions/setup-node@v4
        with:
          node-version: $
          cache: 'pnpm'
      - name: Dependencies
        run: pnpm install -r
      - name: Test $ $
        run: npm run build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: $
